[{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10422267","html_url":"https://github.com/owncloud/core/issues/457#issuecomment-10422267","issue_url":"https://api.github.com/repos/owncloud/core/issues/457","id":10422267,"user":{"login":"blizzz","id":2184312,"avatar_url":"https://gravatar.com/avatar/1898b25a9cb3aa1a0f0febd1359910b9?d=https%3a%2f%2fidenticons.github.com%2fca03acec6deadf508b75eb0cf9ba036c.png&r=x","gravatar_id":"1898b25a9cb3aa1a0f0febd1359910b9","url":"https://api.github.com/users/blizzz","html_url":"https://github.com/blizzz","followers_url":"https://api.github.com/users/blizzz/followers","following_url":"https://api.github.com/users/blizzz/following{/other_user}","gists_url":"https://api.github.com/users/blizzz/gists{/gist_id}","starred_url":"https://api.github.com/users/blizzz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blizzz/subscriptions","organizations_url":"https://api.github.com/users/blizzz/orgs","repos_url":"https://api.github.com/users/blizzz/repos","events_url":"https://api.github.com/users/blizzz/events{/privacy}","received_events_url":"https://api.github.com/users/blizzz/received_events","type":"user","site_admin":false},"created_at":"2012-11-15t19:42:35z","updated_at":"2012-11-15t19:42:35z","body":"works fine with mysql, so probably something dependent on sqlite. we have another bug with the same error message (https://github.com/owncloud/core/issues/216), not necessarilly related, but maybe."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10442178","html_url":"https://github.com/owncloud/core/issues/457#issuecomment-10442178","issue_url":"https://api.github.com/repos/owncloud/core/issues/457","id":10442178,"user":{"login":"archme","id":238723,"avatar_url":"https://gravatar.com/avatar/57ac72fb269dd6ffea8dcbb0bad6335d?d=https%3a%2f%2fidenticons.github.com%2f1049a9cd8dd09f48a6ef5170f0a772af.png&r=x","gravatar_id":"57ac72fb269dd6ffea8dcbb0bad6335d","url":"https://api.github.com/users/archme","html_url":"https://github.com/archme","followers_url":"https://api.github.com/users/archme/followers","following_url":"https://api.github.com/users/archme/following{/other_user}","gists_url":"https://api.github.com/users/archme/gists{/gist_id}","starred_url":"https://api.github.com/users/archme/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/archme/subscriptions","organizations_url":"https://api.github.com/users/archme/orgs","repos_url":"https://api.github.com/users/archme/repos","events_url":"https://api.github.com/users/archme/events{/privacy}","received_events_url":"https://api.github.com/users/archme/received_events","type":"user","site_admin":false},"created_at":"2012-11-16t10:04:44z","updated_at":"2012-11-16t10:04:44z","body":"tried to reproduce with postgresql (9.2.1).\r\nwith this db backend owncloud is nearly unusable.\r\n\r\nto many bugs to list them all.\r\ncalender, contacts do not work.\r\nafter creating first folder i get:\r\ndb error: \"mdb2 error: no such field\"\r\noffending command was: delete from \"oc_properties\" where \"propertypath\" = \"/shared\"\r\n..."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10451455","html_url":"https://github.com/owncloud/core/issues/457#issuecomment-10451455","issue_url":"https://api.github.com/repos/owncloud/core/issues/457","id":10451455,"user":{"login":"emerzh","id":177003,"avatar_url":"https://gravatar.com/avatar/8be57cd98b8864ebcc903ae7106ea420?d=https%3a%2f%2fidenticons.github.com%2f35789e0e5e2d4b3b73630bb168f26d12.png&r=x","gravatar_id":"8be57cd98b8864ebcc903ae7106ea420","url":"https://api.github.com/users/emerzh","html_url":"https://github.com/emerzh","followers_url":"https://api.github.com/users/emerzh/followers","following_url":"https://api.github.com/users/emerzh/following{/other_user}","gists_url":"https://api.github.com/users/emerzh/gists{/gist_id}","starred_url":"https://api.github.com/users/emerzh/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/emerzh/subscriptions","organizations_url":"https://api.github.com/users/emerzh/orgs","repos_url":"https://api.github.com/users/emerzh/repos","events_url":"https://api.github.com/users/emerzh/events{/privacy}","received_events_url":"https://api.github.com/users/emerzh/received_events","type":"user","site_admin":false},"created_at":"2012-11-16t15:54:03z","updated_at":"2012-11-16t15:54:32z","body":"@archme the bug with postgresql is corrected ...  (#430)\r\n\r\nsooo many postgres bug... but none of them are in the issue tracker.... \r\n\r\nhttps://github.com/owncloud/core/issues/search?q=postgresql\r\n\r\nplease help us make oc a better software :)\r\n\r\n\r\nfor the sqlite problem... are you sure that nothing else has open the db? an editor, another client, another session?\r\n\r\n"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10455342","html_url":"https://github.com/owncloud/core/issues/457#issuecomment-10455342","issue_url":"https://api.github.com/repos/owncloud/core/issues/457","id":10455342,"user":{"login":"archme","id":238723,"avatar_url":"https://gravatar.com/avatar/57ac72fb269dd6ffea8dcbb0bad6335d?d=https%3a%2f%2fidenticons.github.com%2f1049a9cd8dd09f48a6ef5170f0a772af.png&r=x","gravatar_id":"57ac72fb269dd6ffea8dcbb0bad6335d","url":"https://api.github.com/users/archme","html_url":"https://github.com/archme","followers_url":"https://api.github.com/users/archme/followers","following_url":"https://api.github.com/users/archme/following{/other_user}","gists_url":"https://api.github.com/users/archme/gists{/gist_id}","starred_url":"https://api.github.com/users/archme/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/archme/subscriptions","organizations_url":"https://api.github.com/users/archme/orgs","repos_url":"https://api.github.com/users/archme/repos","events_url":"https://api.github.com/users/archme/events{/privacy}","received_events_url":"https://api.github.com/users/archme/received_events","type":"user","site_admin":false},"created_at":"2012-11-16t17:45:14z","updated_at":"2012-11-16t17:45:14z","body":"@emerzh, sorry for my \"rude\" words, i exaggerated.\r\nnot sure how to get the fixed version.\r\ni now used: git clone -b stable45 https://github.com/owncloud/core.git\r\nif this is the right version, i could immediately post a new bug ;)"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10456172","html_url":"https://github.com/owncloud/core/issues/457#issuecomment-10456172","issue_url":"https://api.github.com/repos/owncloud/core/issues/457","id":10456172,"user":{"login":"emerzh","id":177003,"avatar_url":"https://gravatar.com/avatar/8be57cd98b8864ebcc903ae7106ea420?d=https%3a%2f%2fidenticons.github.com%2f35789e0e5e2d4b3b73630bb168f26d12.png&r=x","gravatar_id":"8be57cd98b8864ebcc903ae7106ea420","url":"https://api.github.com/users/emerzh","html_url":"https://github.com/emerzh","followers_url":"https://api.github.com/users/emerzh/followers","following_url":"https://api.github.com/users/emerzh/following{/other_user}","gists_url":"https://api.github.com/users/emerzh/gists{/gist_id}","starred_url":"https://api.github.com/users/emerzh/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/emerzh/subscriptions","organizations_url":"https://api.github.com/users/emerzh/orgs","repos_url":"https://api.github.com/users/emerzh/repos","events_url":"https://api.github.com/users/emerzh/events{/privacy}","received_events_url":"https://api.github.com/users/emerzh/received_events","type":"user","site_admin":false},"created_at":"2012-11-16t18:09:57z","updated_at":"2012-11-16t18:09:57z","body":"@archme yes it was applied on stable45....(and not yet released in a .x version)\r\ncould you do a pull on stable45 ? the patch was applied less than 1 day ago....\r\n\r\nand give me the result of \r\n``` \r\ngit rev-parse --short head\r\n\r\n```"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10461268","html_url":"https://github.com/owncloud/core/issues/457#issuecomment-10461268","issue_url":"https://api.github.com/repos/owncloud/core/issues/457","id":10461268,"user":{"login":"archme","id":238723,"avatar_url":"https://gravatar.com/avatar/57ac72fb269dd6ffea8dcbb0bad6335d?d=https%3a%2f%2fidenticons.github.com%2f1049a9cd8dd09f48a6ef5170f0a772af.png&r=x","gravatar_id":"57ac72fb269dd6ffea8dcbb0bad6335d","url":"https://api.github.com/users/archme","html_url":"https://github.com/archme","followers_url":"https://api.github.com/users/archme/followers","following_url":"https://api.github.com/users/archme/following{/other_user}","gists_url":"https://api.github.com/users/archme/gists{/gist_id}","starred_url":"https://api.github.com/users/archme/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/archme/subscriptions","organizations_url":"https://api.github.com/users/archme/orgs","repos_url":"https://api.github.com/users/archme/repos","events_url":"https://api.github.com/users/archme/events{/privacy}","received_events_url":"https://api.github.com/users/archme/received_events","type":"user","site_admin":false},"created_at":"2012-11-16t20:38:08z","updated_at":"2012-11-16t20:39:31z","body":"i now test with this command: git clone https://github.com/owncloud/core.git\r\nwith this version, the sqlite bug is still there on my setup.\r\nwith postgresql it works fine now.\r\n\r\n>for the sqlite problem... are you sure that nothing else has open the db? an editor, another client, another session?\r\n\r\nlsof /home/www/owncloud/data/owncloud.db\r\nuwsgi   10146 http   10uw  reg    8,5    29696 8398802 /home/www/owncloud/data/owncloud.db\r\n\r\nps ax|grep 10146\r\n10146 ?        s      0:00 /usr/bin/uwsgi --ini owncloud.example.com.ini\r\n\r\nthere also exists /home/www/owncloud/data/owncloud.db-journal (also locked by the same pid)\r\nand i have 100% cpu-io-wait, until i kill the pid"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10461460","html_url":"https://github.com/owncloud/core/issues/457#issuecomment-10461460","issue_url":"https://api.github.com/repos/owncloud/core/issues/457","id":10461460,"user":{"login":"archme","id":238723,"avatar_url":"https://gravatar.com/avatar/57ac72fb269dd6ffea8dcbb0bad6335d?d=https%3a%2f%2fidenticons.github.com%2f1049a9cd8dd09f48a6ef5170f0a772af.png&r=x","gravatar_id":"57ac72fb269dd6ffea8dcbb0bad6335d","url":"https://api.github.com/users/archme","html_url":"https://github.com/archme","followers_url":"https://api.github.com/users/archme/followers","following_url":"https://api.github.com/users/archme/following{/other_user}","gists_url":"https://api.github.com/users/archme/gists{/gist_id}","starred_url":"https://api.github.com/users/archme/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/archme/subscriptions","organizations_url":"https://api.github.com/users/archme/orgs","repos_url":"https://api.github.com/users/archme/repos","events_url":"https://api.github.com/users/archme/events{/privacy}","received_events_url":"https://api.github.com/users/archme/received_events","type":"user","site_admin":false},"created_at":"2012-11-16t20:43:14z","updated_at":"2012-11-16t20:43:14z","body":"@emerzh, did you also test with sqlite backend ?"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10461641","html_url":"https://github.com/owncloud/core/issues/457#issuecomment-10461641","issue_url":"https://api.github.com/repos/owncloud/core/issues/457","id":10461641,"user":{"login":"emerzh","id":177003,"avatar_url":"https://gravatar.com/avatar/8be57cd98b8864ebcc903ae7106ea420?d=https%3a%2f%2fidenticons.github.com%2f35789e0e5e2d4b3b73630bb168f26d12.png&r=x","gravatar_id":"8be57cd98b8864ebcc903ae7106ea420","url":"https://api.github.com/users/emerzh","html_url":"https://github.com/emerzh","followers_url":"https://api.github.com/users/emerzh/followers","following_url":"https://api.github.com/users/emerzh/following{/other_user}","gists_url":"https://api.github.com/users/emerzh/gists{/gist_id}","starred_url":"https://api.github.com/users/emerzh/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/emerzh/subscriptions","organizations_url":"https://api.github.com/users/emerzh/orgs","repos_url":"https://api.github.com/users/emerzh/repos","events_url":"https://api.github.com/users/emerzh/events{/privacy}","received_events_url":"https://api.github.com/users/emerzh/received_events","type":"user","site_admin":false},"created_at":"2012-11-16t20:49:22z","updated_at":"2012-11-16t20:49:22z","body":"@archme for the fix i was talking about pg...\r\n\r\n\r\nfor your sqlite pbm, i don't know enough the uwsgi way of working... but i think it seems to be one part of the problem....\r\n\r\nin sqlite 2 different process cannot use the db at the same time\r\n"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/14249883","html_url":"https://github.com/owncloud/core/issues/457#issuecomment-14249883","issue_url":"https://api.github.com/repos/owncloud/core/issues/457","id":14249883,"user":{"login":"jancborchardt","id":925062,"avatar_url":"https://gravatar.com/avatar/2fd3f4d5d762955e5b603794a888fa97?d=https%3a%2f%2fidenticons.github.com%2f84ec51f9ceed468217d4e13abf78da9c.png&r=x","gravatar_id":"2fd3f4d5d762955e5b603794a888fa97","url":"https://api.github.com/users/jancborchardt","html_url":"https://github.com/jancborchardt","followers_url":"https://api.github.com/users/jancborchardt/followers","following_url":"https://api.github.com/users/jancborchardt/following{/other_user}","gists_url":"https://api.github.com/users/jancborchardt/gists{/gist_id}","starred_url":"https://api.github.com/users/jancborchardt/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jancborchardt/subscriptions","organizations_url":"https://api.github.com/users/jancborchardt/orgs","repos_url":"https://api.github.com/users/jancborchardt/repos","events_url":"https://api.github.com/users/jancborchardt/events{/privacy}","received_events_url":"https://api.github.com/users/jancborchardt/received_events","type":"user","site_admin":false},"created_at":"2013-02-28t18:48:05z","updated_at":"2013-02-28t18:48:05z","body":"@archme is this still an issue with the current stable 4.5.7?"}]