[{"url":"https://api.github.com/repos/owncloud/core/issues/comments/9843868","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-9843868","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":9843868,"user":{"login":"mtrichards","id":1818977,"avatar_url":"https://gravatar.com/avatar/a1655fd2e819638708ee854fa941008b?d=https%3a%2f%2fidenticons.github.com%2fa75d8baded229745ad65d43f7a7975df.png&r=x","gravatar_id":"a1655fd2e819638708ee854fa941008b","url":"https://api.github.com/users/mtrichards","html_url":"https://github.com/mtrichards","followers_url":"https://api.github.com/users/mtrichards/followers","following_url":"https://api.github.com/users/mtrichards/following{/other_user}","gists_url":"https://api.github.com/users/mtrichards/gists{/gist_id}","starred_url":"https://api.github.com/users/mtrichards/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mtrichards/subscriptions","organizations_url":"https://api.github.com/users/mtrichards/orgs","repos_url":"https://api.github.com/users/mtrichards/repos","events_url":"https://api.github.com/users/mtrichards/events{/privacy}","received_events_url":"https://api.github.com/users/mtrichards/received_events","type":"user","site_admin":false},"created_at":"2012-10-28t08:58:18z","updated_at":"2012-10-28t08:58:18z","body":"more info: it's when accessing the link, it only happens with ldap users, some kind of \r\nissue with the user mapping i think. \r\nall the ldap users are in a local group, the can share in owncloud, when they \r\nshare a link the link fails when accessing. the local user, the admin, has no \r\nissues though.\r\n"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/9844099","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-9844099","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":9844099,"user":{"login":"blizzz","id":2184312,"avatar_url":"https://gravatar.com/avatar/1898b25a9cb3aa1a0f0febd1359910b9?d=https%3a%2f%2fidenticons.github.com%2fca03acec6deadf508b75eb0cf9ba036c.png&r=x","gravatar_id":"1898b25a9cb3aa1a0f0febd1359910b9","url":"https://api.github.com/users/blizzz","html_url":"https://github.com/blizzz","followers_url":"https://api.github.com/users/blizzz/followers","following_url":"https://api.github.com/users/blizzz/following{/other_user}","gists_url":"https://api.github.com/users/blizzz/gists{/gist_id}","starred_url":"https://api.github.com/users/blizzz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blizzz/subscriptions","organizations_url":"https://api.github.com/users/blizzz/orgs","repos_url":"https://api.github.com/users/blizzz/repos","events_url":"https://api.github.com/users/blizzz/events{/privacy}","received_events_url":"https://api.github.com/users/blizzz/received_events","type":"user","site_admin":false},"created_at":"2012-10-28t09:40:00z","updated_at":"2012-10-28t09:40:00z","body":"do i understand correctly: as ldap user, you share a file by link. the link however throws an 404 (\"owncloud cloud not found\")? and it happens using 4.5.1?"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/9845987","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-9845987","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":9845987,"user":{"login":"blizzz","id":2184312,"avatar_url":"https://gravatar.com/avatar/1898b25a9cb3aa1a0f0febd1359910b9?d=https%3a%2f%2fidenticons.github.com%2fca03acec6deadf508b75eb0cf9ba036c.png&r=x","gravatar_id":"1898b25a9cb3aa1a0f0febd1359910b9","url":"https://api.github.com/users/blizzz","html_url":"https://github.com/blizzz","followers_url":"https://api.github.com/users/blizzz/followers","following_url":"https://api.github.com/users/blizzz/following{/other_user}","gists_url":"https://api.github.com/users/blizzz/gists{/gist_id}","starred_url":"https://api.github.com/users/blizzz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blizzz/subscriptions","organizations_url":"https://api.github.com/users/blizzz/orgs","repos_url":"https://api.github.com/users/blizzz/repos","events_url":"https://api.github.com/users/blizzz/events{/privacy}","received_events_url":"https://api.github.com/users/blizzz/received_events","type":"user","site_admin":false},"created_at":"2012-10-28t14:00:25z","updated_at":"2012-10-28t14:00:25z","body":"might be related to #89"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/9859698","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-9859698","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":9859698,"user":{"login":"mtrichards","id":1818977,"avatar_url":"https://gravatar.com/avatar/a1655fd2e819638708ee854fa941008b?d=https%3a%2f%2fidenticons.github.com%2fa75d8baded229745ad65d43f7a7975df.png&r=x","gravatar_id":"a1655fd2e819638708ee854fa941008b","url":"https://api.github.com/users/mtrichards","html_url":"https://github.com/mtrichards","followers_url":"https://api.github.com/users/mtrichards/followers","following_url":"https://api.github.com/users/mtrichards/following{/other_user}","gists_url":"https://api.github.com/users/mtrichards/gists{/gist_id}","starred_url":"https://api.github.com/users/mtrichards/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mtrichards/subscriptions","organizations_url":"https://api.github.com/users/mtrichards/orgs","repos_url":"https://api.github.com/users/mtrichards/repos","events_url":"https://api.github.com/users/mtrichards/events{/privacy}","received_events_url":"https://api.github.com/users/mtrichards/received_events","type":"user","site_admin":false},"created_at":"2012-10-29t09:04:28z","updated_at":"2012-10-29t09:04:28z","body":"more info:\r\ni've found the issue only to occur when a user, ldap or local, shares a file \r\nvia link within a directory shared by a other user within owncloud. \r\nthere are no problems with files outside of shared directories.\r\nso the steps to reproduce would be the following.\r\n- create 2 users (user1, user2) both member of the same group (group1)\r\n- login as user1 and create a directory\r\n- share the directory with group1\r\n- logout and login as user2, go to the shared directory\r\n- upload a file and share the file with a link\r\n- open a second browser and open the link\r\n- the error \"cloud not found\" appears, the file cannot be downloaded\r\ni have reproduced this on a second owncloud instance on a different server. any \r\nviewer app was disabled, only the following apps where active.\r\n- archive support 0.2\r\n- ldap user and group backend 0.3.0.0\r\n- share files 0.3.3\r\n- versions 1.0.2\r\nhope this helps.\r\n"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/9866863","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-9866863","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":9866863,"user":{"login":"blizzz","id":2184312,"avatar_url":"https://gravatar.com/avatar/1898b25a9cb3aa1a0f0febd1359910b9?d=https%3a%2f%2fidenticons.github.com%2fca03acec6deadf508b75eb0cf9ba036c.png&r=x","gravatar_id":"1898b25a9cb3aa1a0f0febd1359910b9","url":"https://api.github.com/users/blizzz","html_url":"https://github.com/blizzz","followers_url":"https://api.github.com/users/blizzz/followers","following_url":"https://api.github.com/users/blizzz/following{/other_user}","gists_url":"https://api.github.com/users/blizzz/gists{/gist_id}","starred_url":"https://api.github.com/users/blizzz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blizzz/subscriptions","organizations_url":"https://api.github.com/users/blizzz/orgs","repos_url":"https://api.github.com/users/blizzz/repos","events_url":"https://api.github.com/users/blizzz/events{/privacy}","received_events_url":"https://api.github.com/users/blizzz/received_events","type":"user","site_admin":false},"created_at":"2012-10-29t13:52:19z","updated_at":"2012-10-29t13:52:19z","body":"yes, this behaviour i can confirm.\r\nit's an issue within sharing, not related to ldap.\r\n@mtgap @schiesbn is it known or do you know where the problem could be?"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/9903699","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-9903699","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":9903699,"user":{"login":"schiesbn","id":1589737,"avatar_url":"https://gravatar.com/avatar/8912b598c7b32dd25b87fd168e0b06b2?d=https%3a%2f%2fidenticons.github.com%2f0a323047dbe8329db30eae8dbe96e55e.png&r=x","gravatar_id":"8912b598c7b32dd25b87fd168e0b06b2","url":"https://api.github.com/users/schiesbn","html_url":"https://github.com/schiesbn","followers_url":"https://api.github.com/users/schiesbn/followers","following_url":"https://api.github.com/users/schiesbn/following{/other_user}","gists_url":"https://api.github.com/users/schiesbn/gists{/gist_id}","starred_url":"https://api.github.com/users/schiesbn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/schiesbn/subscriptions","organizations_url":"https://api.github.com/users/schiesbn/orgs","repos_url":"https://api.github.com/users/schiesbn/repos","events_url":"https://api.github.com/users/schiesbn/events{/privacy}","received_events_url":"https://api.github.com/users/schiesbn/received_events","type":"user","site_admin":false},"created_at":"2012-10-30t12:26:29z","updated_at":"2012-10-30t12:26:29z","body":"i fixed this a few days ago (https://github.com/owncloud/core/commit/3b9c10dcf61fb633acc80f26b1ee151b6429589e)\r\n\r\nthe fix is already part of 4.5.1a but _not_ in 4.5.1! can you try it with 4.5.1a or with stable45 branch from git?"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/9914326","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-9914326","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":9914326,"user":{"login":"blizzz","id":2184312,"avatar_url":"https://gravatar.com/avatar/1898b25a9cb3aa1a0f0febd1359910b9?d=https%3a%2f%2fidenticons.github.com%2fca03acec6deadf508b75eb0cf9ba036c.png&r=x","gravatar_id":"1898b25a9cb3aa1a0f0febd1359910b9","url":"https://api.github.com/users/blizzz","html_url":"https://github.com/blizzz","followers_url":"https://api.github.com/users/blizzz/followers","following_url":"https://api.github.com/users/blizzz/following{/other_user}","gists_url":"https://api.github.com/users/blizzz/gists{/gist_id}","starred_url":"https://api.github.com/users/blizzz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blizzz/subscriptions","organizations_url":"https://api.github.com/users/blizzz/orgs","repos_url":"https://api.github.com/users/blizzz/repos","events_url":"https://api.github.com/users/blizzz/events{/privacy}","received_events_url":"https://api.github.com/users/blizzz/received_events","type":"user","site_admin":false},"created_at":"2012-10-30t17:13:53z","updated_at":"2012-10-30t17:13:53z","body":"i experienced it with the stable45 branch."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10010597","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-10010597","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":10010597,"user":{"login":"tareko","id":1128840,"avatar_url":"https://gravatar.com/avatar/00c5703b2ad0cfeb83c3550b7e3f25ce?d=https%3a%2f%2fidenticons.github.com%2f596dc97c5e3b7984af4fabfab504f2f9.png&r=x","gravatar_id":"00c5703b2ad0cfeb83c3550b7e3f25ce","url":"https://api.github.com/users/tareko","html_url":"https://github.com/tareko","followers_url":"https://api.github.com/users/tareko/followers","following_url":"https://api.github.com/users/tareko/following{/other_user}","gists_url":"https://api.github.com/users/tareko/gists{/gist_id}","starred_url":"https://api.github.com/users/tareko/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tareko/subscriptions","organizations_url":"https://api.github.com/users/tareko/orgs","repos_url":"https://api.github.com/users/tareko/repos","events_url":"https://api.github.com/users/tareko/events{/privacy}","received_events_url":"https://api.github.com/users/tareko/received_events","type":"user","site_admin":false},"created_at":"2012-11-02t10:47:24z","updated_at":"2012-11-02t10:47:24z","body":"this problem exists for me as well despite clearly having the code from https://github.com/owncloud/core/issues/117#issuecomment-9903699"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10203809","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-10203809","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":10203809,"user":{"login":"blizzz","id":2184312,"avatar_url":"https://gravatar.com/avatar/1898b25a9cb3aa1a0f0febd1359910b9?d=https%3a%2f%2fidenticons.github.com%2fca03acec6deadf508b75eb0cf9ba036c.png&r=x","gravatar_id":"1898b25a9cb3aa1a0f0febd1359910b9","url":"https://api.github.com/users/blizzz","html_url":"https://github.com/blizzz","followers_url":"https://api.github.com/users/blizzz/followers","following_url":"https://api.github.com/users/blizzz/following{/other_user}","gists_url":"https://api.github.com/users/blizzz/gists{/gist_id}","starred_url":"https://api.github.com/users/blizzz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blizzz/subscriptions","organizations_url":"https://api.github.com/users/blizzz/orgs","repos_url":"https://api.github.com/users/blizzz/repos","events_url":"https://api.github.com/users/blizzz/events{/privacy}","received_events_url":"https://api.github.com/users/blizzz/received_events","type":"user","site_admin":false},"created_at":"2012-11-08t20:36:18z","updated_at":"2012-11-08t20:36:18z","body":"@schiesbn do you have  an update?"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10280806","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-10280806","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":10280806,"user":{"login":"schiesbn","id":1589737,"avatar_url":"https://gravatar.com/avatar/8912b598c7b32dd25b87fd168e0b06b2?d=https%3a%2f%2fidenticons.github.com%2f0a323047dbe8329db30eae8dbe96e55e.png&r=x","gravatar_id":"8912b598c7b32dd25b87fd168e0b06b2","url":"https://api.github.com/users/schiesbn","html_url":"https://github.com/schiesbn","followers_url":"https://api.github.com/users/schiesbn/followers","following_url":"https://api.github.com/users/schiesbn/following{/other_user}","gists_url":"https://api.github.com/users/schiesbn/gists{/gist_id}","starred_url":"https://api.github.com/users/schiesbn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/schiesbn/subscriptions","organizations_url":"https://api.github.com/users/schiesbn/orgs","repos_url":"https://api.github.com/users/schiesbn/repos","events_url":"https://api.github.com/users/schiesbn/events{/privacy}","received_events_url":"https://api.github.com/users/schiesbn/received_events","type":"user","site_admin":false},"created_at":"2012-11-12t09:14:13z","updated_at":"2012-11-12t09:14:13z","body":"i can reproduce it. there seems to be more problems related to file creation in shared folders (see issue #325). as i understood @mtgap this is something which can't be solved that easily with the code we have at the moment. maybe we have to wait for the new filesystem cache. @mtgap can you have a look at it. what do you think?"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10281881","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-10281881","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":10281881,"user":{"login":"blizzz","id":2184312,"avatar_url":"https://gravatar.com/avatar/1898b25a9cb3aa1a0f0febd1359910b9?d=https%3a%2f%2fidenticons.github.com%2fca03acec6deadf508b75eb0cf9ba036c.png&r=x","gravatar_id":"1898b25a9cb3aa1a0f0febd1359910b9","url":"https://api.github.com/users/blizzz","html_url":"https://github.com/blizzz","followers_url":"https://api.github.com/users/blizzz/followers","following_url":"https://api.github.com/users/blizzz/following{/other_user}","gists_url":"https://api.github.com/users/blizzz/gists{/gist_id}","starred_url":"https://api.github.com/users/blizzz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blizzz/subscriptions","organizations_url":"https://api.github.com/users/blizzz/orgs","repos_url":"https://api.github.com/users/blizzz/repos","events_url":"https://api.github.com/users/blizzz/events{/privacy}","received_events_url":"https://api.github.com/users/blizzz/received_events","type":"user","site_admin":false},"created_at":"2012-11-12t09:58:43z","updated_at":"2012-11-12t09:58:43z","body":"honestly, it's a basic functionality and it might be hard to understand for users to wait for yet another release for fully working sharing. especially since it is entitled as a supported app."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10287153","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-10287153","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":10287153,"user":{"login":"mtgap","id":1097106,"avatar_url":"https://gravatar.com/avatar/454a73ee5feeb428d0c163a48903332c?d=https%3a%2f%2fidenticons.github.com%2f52d29a66f285a1d61125dd69ac0766b2.png&r=x","gravatar_id":"454a73ee5feeb428d0c163a48903332c","url":"https://api.github.com/users/mtgap","html_url":"https://github.com/mtgap","followers_url":"https://api.github.com/users/mtgap/followers","following_url":"https://api.github.com/users/mtgap/following{/other_user}","gists_url":"https://api.github.com/users/mtgap/gists{/gist_id}","starred_url":"https://api.github.com/users/mtgap/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mtgap/subscriptions","organizations_url":"https://api.github.com/users/mtgap/orgs","repos_url":"https://api.github.com/users/mtgap/repos","events_url":"https://api.github.com/users/mtgap/events{/privacy}","received_events_url":"https://api.github.com/users/mtgap/received_events","type":"user","site_admin":false},"created_at":"2012-11-12t13:24:45z","updated_at":"2012-11-12t13:24:45z","body":"@schiesbn this isn't related to issue #325 i'll try to look at it later, but my time is limited this week."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10595554","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-10595554","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":10595554,"user":{"login":"schiesbn","id":1589737,"avatar_url":"https://gravatar.com/avatar/8912b598c7b32dd25b87fd168e0b06b2?d=https%3a%2f%2fidenticons.github.com%2f0a323047dbe8329db30eae8dbe96e55e.png&r=x","gravatar_id":"8912b598c7b32dd25b87fd168e0b06b2","url":"https://api.github.com/users/schiesbn","html_url":"https://github.com/schiesbn","followers_url":"https://api.github.com/users/schiesbn/followers","following_url":"https://api.github.com/users/schiesbn/following{/other_user}","gists_url":"https://api.github.com/users/schiesbn/gists{/gist_id}","starred_url":"https://api.github.com/users/schiesbn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/schiesbn/subscriptions","organizations_url":"https://api.github.com/users/schiesbn/orgs","repos_url":"https://api.github.com/users/schiesbn/repos","events_url":"https://api.github.com/users/schiesbn/events{/privacy}","received_events_url":"https://api.github.com/users/schiesbn/received_events","type":"user","site_admin":false},"created_at":"2012-11-21t12:47:07z","updated_at":"2012-11-21t12:47:07z","body":"it is probably the same as https://github.com/owncloud/core/issues/382 so this should also be solved with https://github.com/owncloud/core/issues/380, right?"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10631684","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-10631684","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":10631684,"user":{"login":"butonic","id":956847,"avatar_url":"https://gravatar.com/avatar/9760c134cabf66e10dbba06d7525f5c7?d=https%3a%2f%2fidenticons.github.com%2f92925ec1ad893739ed57986f18e2f060.png&r=x","gravatar_id":"9760c134cabf66e10dbba06d7525f5c7","url":"https://api.github.com/users/butonic","html_url":"https://github.com/butonic","followers_url":"https://api.github.com/users/butonic/followers","following_url":"https://api.github.com/users/butonic/following{/other_user}","gists_url":"https://api.github.com/users/butonic/gists{/gist_id}","starred_url":"https://api.github.com/users/butonic/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/butonic/subscriptions","organizations_url":"https://api.github.com/users/butonic/orgs","repos_url":"https://api.github.com/users/butonic/repos","events_url":"https://api.github.com/users/butonic/events{/privacy}","received_events_url":"https://api.github.com/users/butonic/received_events","type":"user","site_admin":false},"created_at":"2012-11-22t11:35:14z","updated_at":"2012-11-22t11:35:14z","body":"@schiesbn could you test #380 with regard to this issue and give me your thumbs up when this is solved?"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/10723338","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-10723338","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":10723338,"user":{"login":"schiesbn","id":1589737,"avatar_url":"https://gravatar.com/avatar/8912b598c7b32dd25b87fd168e0b06b2?d=https%3a%2f%2fidenticons.github.com%2f0a323047dbe8329db30eae8dbe96e55e.png&r=x","gravatar_id":"8912b598c7b32dd25b87fd168e0b06b2","url":"https://api.github.com/users/schiesbn","html_url":"https://github.com/schiesbn","followers_url":"https://api.github.com/users/schiesbn/followers","following_url":"https://api.github.com/users/schiesbn/following{/other_user}","gists_url":"https://api.github.com/users/schiesbn/gists{/gist_id}","starred_url":"https://api.github.com/users/schiesbn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/schiesbn/subscriptions","organizations_url":"https://api.github.com/users/schiesbn/orgs","repos_url":"https://api.github.com/users/schiesbn/repos","events_url":"https://api.github.com/users/schiesbn/events{/privacy}","received_events_url":"https://api.github.com/users/schiesbn/received_events","type":"user","site_admin":false},"created_at":"2012-11-26t16:55:17z","updated_at":"2012-11-26t16:55:17z","body":"fix will be released with owncloud 4.5.3"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/12886344","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-12886344","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":12886344,"user":{"login":"herr-lehmann","id":567302,"avatar_url":"https://gravatar.com/avatar/222560b8a52cb764836ce388cd043d87?d=https%3a%2f%2fidenticons.github.com%2f09b24d85e16226316906da029eba34f4.png&r=x","gravatar_id":"222560b8a52cb764836ce388cd043d87","url":"https://api.github.com/users/herr-lehmann","html_url":"https://github.com/herr-lehmann","followers_url":"https://api.github.com/users/herr-lehmann/followers","following_url":"https://api.github.com/users/herr-lehmann/following{/other_user}","gists_url":"https://api.github.com/users/herr-lehmann/gists{/gist_id}","starred_url":"https://api.github.com/users/herr-lehmann/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/herr-lehmann/subscriptions","organizations_url":"https://api.github.com/users/herr-lehmann/orgs","repos_url":"https://api.github.com/users/herr-lehmann/repos","events_url":"https://api.github.com/users/herr-lehmann/events{/privacy}","received_events_url":"https://api.github.com/users/herr-lehmann/received_events","type":"user","site_admin":false},"created_at":"2013-01-30t11:55:21z","updated_at":"2013-01-30t11:55:50z","body":"i'm running 4.5.6 and still encounter this problem. \r\nwe are sharing a folder with mulitple users and all works fine. but when we try to access files by the share link, we get a 404.\r\n![owncloud-404](https://f.cloud.github.com/assets/567302/110770/ddd5cfd2-6ad3-11e2-9756-9a78d05eb0c3.png)\r\n\r\nwhat information do you need to reproduce this issue?\r\n"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/12886527","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-12886527","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":12886527,"user":{"login":"blizzz","id":2184312,"avatar_url":"https://gravatar.com/avatar/1898b25a9cb3aa1a0f0febd1359910b9?d=https%3a%2f%2fidenticons.github.com%2fca03acec6deadf508b75eb0cf9ba036c.png&r=x","gravatar_id":"1898b25a9cb3aa1a0f0febd1359910b9","url":"https://api.github.com/users/blizzz","html_url":"https://github.com/blizzz","followers_url":"https://api.github.com/users/blizzz/followers","following_url":"https://api.github.com/users/blizzz/following{/other_user}","gists_url":"https://api.github.com/users/blizzz/gists{/gist_id}","starred_url":"https://api.github.com/users/blizzz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blizzz/subscriptions","organizations_url":"https://api.github.com/users/blizzz/orgs","repos_url":"https://api.github.com/users/blizzz/repos","events_url":"https://api.github.com/users/blizzz/events{/privacy}","received_events_url":"https://api.github.com/users/blizzz/received_events","type":"user","site_admin":false},"created_at":"2013-01-30t12:01:36z","updated_at":"2013-01-30t12:01:36z","body":"please open a new bug for it. it's likely to have a different  cause."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/13572733","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-13572733","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":13572733,"user":{"login":"yeomos","id":3577190,"avatar_url":"https://gravatar.com/avatar/22fd5050240e13cf212a569210649be7?d=https%3a%2f%2fidenticons.github.com%2f7a69c5ca53b3dad6c50d1773ce781ced.png&r=x","gravatar_id":"22fd5050240e13cf212a569210649be7","url":"https://api.github.com/users/yeomos","html_url":"https://github.com/yeomos","followers_url":"https://api.github.com/users/yeomos/followers","following_url":"https://api.github.com/users/yeomos/following{/other_user}","gists_url":"https://api.github.com/users/yeomos/gists{/gist_id}","starred_url":"https://api.github.com/users/yeomos/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/yeomos/subscriptions","organizations_url":"https://api.github.com/users/yeomos/orgs","repos_url":"https://api.github.com/users/yeomos/repos","events_url":"https://api.github.com/users/yeomos/events{/privacy}","received_events_url":"https://api.github.com/users/yeomos/received_events","type":"user","site_admin":false},"created_at":"2013-02-14t19:11:59z","updated_at":"2013-02-14t19:11:59z","body":"i agree. still broken in 4.5.6"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/13595639","html_url":"https://github.com/owncloud/core/issues/117#issuecomment-13595639","issue_url":"https://api.github.com/repos/owncloud/core/issues/117","id":13595639,"user":{"login":"herr-lehmann","id":567302,"avatar_url":"https://gravatar.com/avatar/222560b8a52cb764836ce388cd043d87?d=https%3a%2f%2fidenticons.github.com%2f09b24d85e16226316906da029eba34f4.png&r=x","gravatar_id":"222560b8a52cb764836ce388cd043d87","url":"https://api.github.com/users/herr-lehmann","html_url":"https://github.com/herr-lehmann","followers_url":"https://api.github.com/users/herr-lehmann/followers","following_url":"https://api.github.com/users/herr-lehmann/following{/other_user}","gists_url":"https://api.github.com/users/herr-lehmann/gists{/gist_id}","starred_url":"https://api.github.com/users/herr-lehmann/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/herr-lehmann/subscriptions","organizations_url":"https://api.github.com/users/herr-lehmann/orgs","repos_url":"https://api.github.com/users/herr-lehmann/repos","events_url":"https://api.github.com/users/herr-lehmann/events{/privacy}","received_events_url":"https://api.github.com/users/herr-lehmann/received_events","type":"user","site_admin":false},"created_at":"2013-02-15t07:46:39z","updated_at":"2013-02-15t07:46:39z","body":"i created a new issue (#1382) for this. please check if you can reproduce this behavior."}]