{"url":"https://api.github.com/repos/owncloud/core/issues/6478","labels_url":"https://api.github.com/repos/owncloud/core/issues/6478/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/6478/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/6478/events","html_url":"https://github.com/owncloud/core/issues/6478","id":24460730,"number":6478,"title":"6.0a can not create new user - the username is already being used","user":{"login":"mat-l","id":5571947,"avatar_url":"https://gravatar.com/avatar/19322f652400c37e04eb8a5a718b6f07?d=https%3a%2f%2fidenticons.github.com%2fd2e7b2020fcec3ff74eb6eda5adef380.png&r=x","gravatar_id":"19322f652400c37e04eb8a5a718b6f07","url":"https://api.github.com/users/mat-l","html_url":"https://github.com/mat-l","followers_url":"https://api.github.com/users/mat-l/followers","following_url":"https://api.github.com/users/mat-l/following{/other_user}","gists_url":"https://api.github.com/users/mat-l/gists{/gist_id}","starred_url":"https://api.github.com/users/mat-l/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mat-l/subscriptions","organizations_url":"https://api.github.com/users/mat-l/orgs","repos_url":"https://api.github.com/users/mat-l/repos","events_url":"https://api.github.com/users/mat-l/events{/privacy}","received_events_url":"https://api.github.com/users/mat-l/received_events","type":"user","site_admin":false},"labels":[{"url":"https://api.github.com/repos/owncloud/core/labels/bug","name":"bug","color":"fc2929"}],"state":"open","assignee":null,"milestone":null,"comments":4,"created_at":"2013-12-18t00:07:19z","updated_at":"2013-12-22t22:10:10z","closed_at":null,"pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"after the update to oc 6.0a i am not abel to create new users.\r\n\r\nthe message is:\r\n\"beim erstellen des benutzers ist ein fehler aufgetreten\r\nthe username is already being used\"\r\n","closed_by":null}