{"url":"https://api.github.com/repos/owncloud/core/issues/6182","labels_url":"https://api.github.com/repos/owncloud/core/issues/6182/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/6182/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/6182/events","html_url":"https://github.com/owncloud/core/issues/6182","id":23716777,"number":6182,"title":"owncloud [6-rc2] lucene_search upgrade failed.","user":{"login":"d3xter","id":159784,"avatar_url":"https://gravatar.com/avatar/f303bc6cd2b266e432eaa9058db85955?d=https%3a%2f%2fidenticons.github.com%2f4ed3e16b119ac468591468b4461b804c.png&r=x","gravatar_id":"f303bc6cd2b266e432eaa9058db85955","url":"https://api.github.com/users/d3xter","html_url":"https://github.com/d3xter","followers_url":"https://api.github.com/users/d3xter/followers","following_url":"https://api.github.com/users/d3xter/following{/other_user}","gists_url":"https://api.github.com/users/d3xter/gists{/gist_id}","starred_url":"https://api.github.com/users/d3xter/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/d3xter/subscriptions","organizations_url":"https://api.github.com/users/d3xter/orgs","repos_url":"https://api.github.com/users/d3xter/repos","events_url":"https://api.github.com/users/d3xter/events{/privacy}","received_events_url":"https://api.github.com/users/d3xter/received_events","type":"user","site_admin":false},"labels":[],"state":"closed","assignee":null,"milestone":null,"comments":2,"created_at":"2013-12-04t14:00:53z","updated_at":"2013-12-04t14:17:20z","closed_at":"2013-12-04t14:10:15z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"i've updated my testing machine to owncloud 6 rc2 and now an error occurs:\r\n\r\n\"failed to upgrade 'lucene_search'\".\r\n\r\nthe table oc_lucene_search is empty,\r\nand the error occurs when running the following statement in \"lucene_search/update.php:15\":\r\n\r\ndelete from oc_lucene_status where fileid in (select fileid from oc_lucene_status group by fileid having count(status) > 0);\r\n\r\nthe error is: \"error 1093 (hy000): you can't specify target table 'oc_lucene_status' for update in from clause\".\r\n\r\ni'm running:\r\nowncloud: git-master\r\napps: git-master\r\nmysql: 5.5.33","closed_by":{"login":"karlitschek","id":867445,"avatar_url":"https://gravatar.com/avatar/87ce2b4531ee1a0c32b50e0d8f049224?d=https%3a%2f%2fidenticons.github.com%2f06e7098636caebfc9c30c9f52eb905df.png&r=x","gravatar_id":"87ce2b4531ee1a0c32b50e0d8f049224","url":"https://api.github.com/users/karlitschek","html_url":"https://github.com/karlitschek","followers_url":"https://api.github.com/users/karlitschek/followers","following_url":"https://api.github.com/users/karlitschek/following{/other_user}","gists_url":"https://api.github.com/users/karlitschek/gists{/gist_id}","starred_url":"https://api.github.com/users/karlitschek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/karlitschek/subscriptions","organizations_url":"https://api.github.com/users/karlitschek/orgs","repos_url":"https://api.github.com/users/karlitschek/repos","events_url":"https://api.github.com/users/karlitschek/events{/privacy}","received_events_url":"https://api.github.com/users/karlitschek/received_events","type":"user","site_admin":false}}