{"url":"https://api.github.com/repos/owncloud/core/issues/4144","labels_url":"https://api.github.com/repos/owncloud/core/issues/4144/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/4144/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/4144/events","html_url":"https://github.com/owncloud/core/issues/4144","id":17016666,"number":4144,"title":"file sync problem with utf8 encoded characters at the beginning","user":{"login":"ego2dot0","id":372364,"avatar_url":"https://gravatar.com/avatar/897f6aad526520d70999edd58dce9bcc?d=https%3a%2f%2fidenticons.github.com%2f1aaceed8137485037845f4d565724e25.png&r=x","gravatar_id":"897f6aad526520d70999edd58dce9bcc","url":"https://api.github.com/users/ego2dot0","html_url":"https://github.com/ego2dot0","followers_url":"https://api.github.com/users/ego2dot0/followers","following_url":"https://api.github.com/users/ego2dot0/following{/other_user}","gists_url":"https://api.github.com/users/ego2dot0/gists{/gist_id}","starred_url":"https://api.github.com/users/ego2dot0/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ego2dot0/subscriptions","organizations_url":"https://api.github.com/users/ego2dot0/orgs","repos_url":"https://api.github.com/users/ego2dot0/repos","events_url":"https://api.github.com/users/ego2dot0/events{/privacy}","received_events_url":"https://api.github.com/users/ego2dot0/received_events","type":"user","site_admin":false},"labels":[],"state":"closed","assignee":null,"milestone":null,"comments":5,"created_at":"2013-07-21t09:05:15z","updated_at":"2013-12-02t11:46:22z","closed_at":"2013-12-02t11:46:22z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"i am using the latest version of owncloud, but the problem exists in every version, even 4.5.x. but i did not investigate the error before.\r\n{\"installed\":\"true\",\"version\":\"5.0.15\",\"versionstring\":\"5.0.9\",\"edition\":\"\"}\r\n\r\nif the file or directory names starts with an utf8 character, the leading special characters are removed. the client stops syncing with the error message \"a file could not be found\". in my case in german and i don't know the exact english message.\r\n\r\nthe web frontend trunks the file or directory too and i am unable to enter the directory with a click. in case of a directory i am able to enter the directory by manipulating the url and execute every task on the files or directory. \r\n\r\nbecause the sync client and the web fronted is affected, it must be some issue with the core. \r\n\r\nby accessing https://domain.name/remote.php/webdav directly, the name is shown trunced, but i can enter the folder by manipulating the url.\r\n\r\nhow to reproduce:\r\ncreate a folder or a file with unicode characters and a space between - like \"укaa\" or \"удaa\". a name like \"удудуд\" is not even shown.\r\n","closed_by":{"login":"karlitschek","id":867445,"avatar_url":"https://gravatar.com/avatar/87ce2b4531ee1a0c32b50e0d8f049224?d=https%3a%2f%2fidenticons.github.com%2f06e7098636caebfc9c30c9f52eb905df.png&r=x","gravatar_id":"87ce2b4531ee1a0c32b50e0d8f049224","url":"https://api.github.com/users/karlitschek","html_url":"https://github.com/karlitschek","followers_url":"https://api.github.com/users/karlitschek/followers","following_url":"https://api.github.com/users/karlitschek/following{/other_user}","gists_url":"https://api.github.com/users/karlitschek/gists{/gist_id}","starred_url":"https://api.github.com/users/karlitschek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/karlitschek/subscriptions","organizations_url":"https://api.github.com/users/karlitschek/orgs","repos_url":"https://api.github.com/users/karlitschek/repos","events_url":"https://api.github.com/users/karlitschek/events{/privacy}","received_events_url":"https://api.github.com/users/karlitschek/received_events","type":"user","site_admin":false}}