{"url":"https://api.github.com/repos/owncloud/core/issues/5224","labels_url":"https://api.github.com/repos/owncloud/core/issues/5224/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/5224/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/5224/events","html_url":"https://github.com/owncloud/core/issues/5224","id":20724940,"number":5224,"title":"[files_encryption] errors in logfiles and config.ini.etmp in oc root when enabling news app","user":{"login":"realrancor","id":2248459,"avatar_url":"https://gravatar.com/avatar/f6105e79dfcfb0fcbabb3db061135c08?d=https%3a%2f%2fidenticons.github.com%2f7a70061016eba74d85c060de0f65212d.png&r=x","gravatar_id":"f6105e79dfcfb0fcbabb3db061135c08","url":"https://api.github.com/users/realrancor","html_url":"https://github.com/realrancor","followers_url":"https://api.github.com/users/realrancor/followers","following_url":"https://api.github.com/users/realrancor/following{/other_user}","gists_url":"https://api.github.com/users/realrancor/gists{/gist_id}","starred_url":"https://api.github.com/users/realrancor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/realrancor/subscriptions","organizations_url":"https://api.github.com/users/realrancor/orgs","repos_url":"https://api.github.com/users/realrancor/repos","events_url":"https://api.github.com/users/realrancor/events{/privacy}","received_events_url":"https://api.github.com/users/realrancor/received_events","type":"user","site_admin":false},"labels":[],"state":"closed","assignee":null,"milestone":null,"comments":7,"created_at":"2013-10-09t06:43:03z","updated_at":"2013-12-06t17:16:26z","closed_at":"2013-12-06t17:16:26z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"hi,\r\n\r\ni don't know if this is a problem of the news or the files_encryption app so i first want to post it in here.\r\n\r\n### expected behaviour\r\nafter enabling the news app no errors / warnings should be shown in the owncloud.log logfile. the config.ini.etmp file should be hidden in the users file list.\r\n\r\n### actual behaviour\r\nafter enabling the news app some errors are shown in the owncloud.log (see logfiles below) and after clicking on the \"news\" navigation icon an config.ini.etmp appears in the users file list.\r\n\r\n### steps to reproduce\r\n1. enabling the files_encryption app and relogin\r\n2. enabling the app framework and the news app\r\n3. clicking on the \"news\" navigation icon\r\n4. have a look at the owncloud.log\r\n\r\n### server configuration\r\noperating system: debian wheezy\r\n\r\nweb server: nginx 1.2.x\r\n\r\ndatabase: mysql 5.4.x\r\n\r\nphp version: 5.4.x\r\n\r\nowncloud version: 5.0.12 with news app 1.605\r\n\r\n### client configuration\r\nbrowser: firefox 24\r\n\r\noperating system: ubuntu\r\n\r\n### logs\r\n#### web server error log\r\n```\r\nnothing relevant in here\r\n```\r\n\r\n#### owncloud log (data/owncloud.log)\r\n```\r\nfatal\tphp\tcould not find owner (uid = \"false\") of file \"/config.ini.etmp\" at /var/www/owncloud/apps/files_encryption/lib/util.php#1213\t2013-10-09t06:30:04+00:00\r\nwarning\tphp\tundefined property: oca\\encryption\\util::$userfilesdir at /var/www/owncloud/apps/files_encryption/lib/util.php#1197\t2013-10-09t06:30:04+00:00\r\nwarning\tphp\tundefined property: oca\\encryption\\util::$userfilesdir at /var/www/owncloud/apps/files_encryption/lib/util.php#1432\r\nwarning\tphp\tfile_get_contents(/var/www/owncloud/data/news/config/config.ini.etmp): failed to open stream: no such file or directory at /var/www/owncloud/lib/files/storage/local.php#113\t2013-10-09t06:32:44+00:00\r\nwarning\tphp\tfile_put_contents(/var/www/owncloud/data/news/config/config.ini): failed to open stream: no such file or directory at /var/www/owncloud/lib/files/storage/local.php#116\t2013-10-09t06:32:43+00:00\r\nwarning\tphp\tfile_get_contents(/var/www/owncloud/data/news/config/config.ini.etmp): failed to open stream: no such file or directory at /var/www/owncloud/lib/files/storage/local.php#113\t2013-10-09t06:32:43+00:00\r\nwarning\tphp\tfile_put_contents(/var/www/owncloud/data/news/config/config.ini): failed to open stream: no such file or directory at /var/www/owncloud/lib/files/storage/local.php#116\t2013-10-09t06:32:41+00:00\r\nwarning\tphp\tfile_get_contents(/var/www/owncloud/data/news/config/config.ini.etmp): failed to open stream: no such file or directory at /var/www/owncloud/lib/files/storage/local.php#113\t2013-10-09t06:32:41+00:00\r\n```\r\n\r\n#### browser log\r\n```\r\nnothing relevant in here\r\n```","closed_by":{"login":"schiesbn","id":1589737,"avatar_url":"https://gravatar.com/avatar/8912b598c7b32dd25b87fd168e0b06b2?d=https%3a%2f%2fidenticons.github.com%2f0a323047dbe8329db30eae8dbe96e55e.png&r=x","gravatar_id":"8912b598c7b32dd25b87fd168e0b06b2","url":"https://api.github.com/users/schiesbn","html_url":"https://github.com/schiesbn","followers_url":"https://api.github.com/users/schiesbn/followers","following_url":"https://api.github.com/users/schiesbn/following{/other_user}","gists_url":"https://api.github.com/users/schiesbn/gists{/gist_id}","starred_url":"https://api.github.com/users/schiesbn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/schiesbn/subscriptions","organizations_url":"https://api.github.com/users/schiesbn/orgs","repos_url":"https://api.github.com/users/schiesbn/repos","events_url":"https://api.github.com/users/schiesbn/events{/privacy}","received_events_url":"https://api.github.com/users/schiesbn/received_events","type":"user","site_admin":false}}