{"url":"https://api.github.com/repos/owncloud/core/issues/4157","labels_url":"https://api.github.com/repos/owncloud/core/issues/4157/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/4157/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/4157/events","html_url":"https://github.com/owncloud/core/issues/4157","id":17059621,"number":4157,"title":"several issues with encryption module","user":{"login":"babelouest","id":3966617,"avatar_url":"https://gravatar.com/avatar/9d5da5c3e67fdfb205d04d0cc091698a?d=https%3a%2f%2fidenticons.github.com%2fc3d0a918b9055d8dd3fd5e8255149046.png&r=x","gravatar_id":"9d5da5c3e67fdfb205d04d0cc091698a","url":"https://api.github.com/users/babelouest","html_url":"https://github.com/babelouest","followers_url":"https://api.github.com/users/babelouest/followers","following_url":"https://api.github.com/users/babelouest/following{/other_user}","gists_url":"https://api.github.com/users/babelouest/gists{/gist_id}","starred_url":"https://api.github.com/users/babelouest/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/babelouest/subscriptions","organizations_url":"https://api.github.com/users/babelouest/orgs","repos_url":"https://api.github.com/users/babelouest/repos","events_url":"https://api.github.com/users/babelouest/events{/privacy}","received_events_url":"https://api.github.com/users/babelouest/received_events","type":"user","site_admin":false},"labels":[{"url":"https://api.github.com/repos/owncloud/core/labels/app%3afiles_encryption","name":"app:files_encryption","color":"02d7e1"}],"state":"closed","assignee":null,"milestone":null,"comments":5,"created_at":"2013-07-22t17:31:14z","updated_at":"2013-10-17t14:32:48z","closed_at":"2013-10-17t14:32:48z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"the encryption module is creating problems in my owncloud.\r\n\r\nit was auto reactivated without notification nor validation from me after 5.0.9 update, although i deactivated it before, then it encrypted the files for a user. when i realized that i deactivated it (again), but the current files of the user are now all encrypted.\r\n\r\nso there are 2 ways to recover the files: by selecting them one by one and retrieve a previous version in history, or reactivating encryption, downloading all files from server, removing them in oc, deactivating encryption, then reuploading them one last time...\r\n\r\nfor me to use encryption would be that we have the control of what files or folders are encrypted. as it is now, i can't use it, that's why i deactivate it.","closed_by":{"login":"karlitschek","id":867445,"avatar_url":"https://gravatar.com/avatar/87ce2b4531ee1a0c32b50e0d8f049224?d=https%3a%2f%2fidenticons.github.com%2f06e7098636caebfc9c30c9f52eb905df.png&r=x","gravatar_id":"87ce2b4531ee1a0c32b50e0d8f049224","url":"https://api.github.com/users/karlitschek","html_url":"https://github.com/karlitschek","followers_url":"https://api.github.com/users/karlitschek/followers","following_url":"https://api.github.com/users/karlitschek/following{/other_user}","gists_url":"https://api.github.com/users/karlitschek/gists{/gist_id}","starred_url":"https://api.github.com/users/karlitschek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/karlitschek/subscriptions","organizations_url":"https://api.github.com/users/karlitschek/orgs","repos_url":"https://api.github.com/users/karlitschek/repos","events_url":"https://api.github.com/users/karlitschek/events{/privacy}","received_events_url":"https://api.github.com/users/karlitschek/received_events","type":"user","site_admin":false}}