{"url":"https://api.github.com/repos/owncloud/core/issues/3633","labels_url":"https://api.github.com/repos/owncloud/core/issues/3633/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/3633/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/3633/events","html_url":"https://github.com/owncloud/core/issues/3633","id":15274248,"number":3633,"title":"fatal: unknown: send of 5 bytes failed with errno=32 broken pipe at unknown#0 ","user":{"login":"serdarevica","id":4640746,"avatar_url":"https://gravatar.com/avatar/87182c831511ad1cd33d3f8cb5da6d2f?d=https%3a%2f%2fidenticons.github.com%2fb7626792c5227935e173bdfb1bae9c76.png&r=x","gravatar_id":"87182c831511ad1cd33d3f8cb5da6d2f","url":"https://api.github.com/users/serdarevica","html_url":"https://github.com/serdarevica","followers_url":"https://api.github.com/users/serdarevica/followers","following_url":"https://api.github.com/users/serdarevica/following{/other_user}","gists_url":"https://api.github.com/users/serdarevica/gists{/gist_id}","starred_url":"https://api.github.com/users/serdarevica/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/serdarevica/subscriptions","organizations_url":"https://api.github.com/users/serdarevica/orgs","repos_url":"https://api.github.com/users/serdarevica/repos","events_url":"https://api.github.com/users/serdarevica/events{/privacy}","received_events_url":"https://api.github.com/users/serdarevica/received_events","type":"user","site_admin":false},"labels":[],"state":"closed","assignee":null,"milestone":null,"comments":1,"created_at":"2013-06-07t14:22:26z","updated_at":"2013-08-16t22:07:31z","closed_at":"2013-08-16t22:07:31z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"hi\r\n\r\n### server configuration\r\noperating system: linux\r\n\r\nweb server: apache\r\n\r\ndatabase: mysql\r\n\r\nphp version: 5.4.16\r\n\r\nowncloud version: 5.07\r\n\r\n### actual behaviour\r\nafter uploading around 2gb of data on cloud i noticed that some of 15-20mb files were not uploaded, (some of them were uploaded correctly) - \r\n\r\nwin client was showing them under error-uploaded.\r\n\r\nin admin log i see: \r\nunknown: send of 5 bytes failed with errno=32 broken pipe at unknown#0 \r\n\r\ni sent those 2 files to my brother and he successfully uploaded them with no problems, as soon as i start uploading those errors appears in log.\r\n\r\nonly difference that we know is his upload speed which is a lot faster.\r\n\r\n\r\nthanks\r\n\r\n\r\nedit: uploading those files was successful via web interface, but the fail again if i try to use final or beta windows client - as well as goodsync via webd\r\n\r\nthanks\r\n","closed_by":{"login":"jancborchardt","id":925062,"avatar_url":"https://gravatar.com/avatar/2fd3f4d5d762955e5b603794a888fa97?d=https%3a%2f%2fidenticons.github.com%2f84ec51f9ceed468217d4e13abf78da9c.png&r=x","gravatar_id":"2fd3f4d5d762955e5b603794a888fa97","url":"https://api.github.com/users/jancborchardt","html_url":"https://github.com/jancborchardt","followers_url":"https://api.github.com/users/jancborchardt/followers","following_url":"https://api.github.com/users/jancborchardt/following{/other_user}","gists_url":"https://api.github.com/users/jancborchardt/gists{/gist_id}","starred_url":"https://api.github.com/users/jancborchardt/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jancborchardt/subscriptions","organizations_url":"https://api.github.com/users/jancborchardt/orgs","repos_url":"https://api.github.com/users/jancborchardt/repos","events_url":"https://api.github.com/users/jancborchardt/events{/privacy}","received_events_url":"https://api.github.com/users/jancborchardt/received_events","type":"user","site_admin":false}}