{"url":"https://api.github.com/repos/owncloud/core/issues/2200","labels_url":"https://api.github.com/repos/owncloud/core/issues/2200/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/2200/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/2200/events","html_url":"https://github.com/owncloud/core/issues/2200","id":11807597,"number":2200,"title":"oc 4.5.7 does not finish setting up the db on centos 6.3","user":{"login":"sherifnagy","id":1666001,"avatar_url":"https://gravatar.com/avatar/0b59a3ac55053765d1833bc71077b621?d=https%3a%2f%2fidenticons.github.com%2f92f4253745fe64392ab9f5651fcf3920.png&r=x","gravatar_id":"0b59a3ac55053765d1833bc71077b621","url":"https://api.github.com/users/sherifnagy","html_url":"https://github.com/sherifnagy","followers_url":"https://api.github.com/users/sherifnagy/followers","following_url":"https://api.github.com/users/sherifnagy/following{/other_user}","gists_url":"https://api.github.com/users/sherifnagy/gists{/gist_id}","starred_url":"https://api.github.com/users/sherifnagy/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/sherifnagy/subscriptions","organizations_url":"https://api.github.com/users/sherifnagy/orgs","repos_url":"https://api.github.com/users/sherifnagy/repos","events_url":"https://api.github.com/users/sherifnagy/events{/privacy}","received_events_url":"https://api.github.com/users/sherifnagy/received_events","type":"user","site_admin":false},"labels":[{"url":"https://api.github.com/repos/owncloud/core/labels/duplicate","name":"duplicate","color":"cccccc"}],"state":"closed","assignee":null,"milestone":null,"comments":1,"created_at":"2013-03-08t14:53:10z","updated_at":"2013-03-08t16:14:41z","closed_at":"2013-03-08t16:14:41z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"i did use the community repo and epel, i managed to install the system however after i go to http://owncloud.domain.com/ and add username and password i get the following error no matter if i am installing using sqlite or mysql\r\n\r\n\"php fatal error:  using $this when not in object context in /var/www/html/owncloud/3rdparty/mdb2/schema/parser.php on line 554\"\r\n\r\nregards,\r\n","closed_by":{"login":"raydiation","id":195053,"avatar_url":"https://gravatar.com/avatar/aa0d7b7302e0d7f4f9513c23b571383a?d=https%3a%2f%2fidenticons.github.com%2faf0a25e27510f77d97634a6bbe653b13.png&r=x","gravatar_id":"aa0d7b7302e0d7f4f9513c23b571383a","url":"https://api.github.com/users/raydiation","html_url":"https://github.com/raydiation","followers_url":"https://api.github.com/users/raydiation/followers","following_url":"https://api.github.com/users/raydiation/following{/other_user}","gists_url":"https://api.github.com/users/raydiation/gists{/gist_id}","starred_url":"https://api.github.com/users/raydiation/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/raydiation/subscriptions","organizations_url":"https://api.github.com/users/raydiation/orgs","repos_url":"https://api.github.com/users/raydiation/repos","events_url":"https://api.github.com/users/raydiation/events{/privacy}","received_events_url":"https://api.github.com/users/raydiation/received_events","type":"user","site_admin":false}}