{"url":"https://api.github.com/repos/owncloud/core/issues/6115","labels_url":"https://api.github.com/repos/owncloud/core/issues/6115/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/6115/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/6115/events","html_url":"https://github.com/owncloud/core/issues/6115","id":23478772,"number":6115,"title":"[oc6-rc1] {\"app\":\"index\",\"message\":\"exception: konnte \\\"documents\\\" nicht aktualisieren. - verursacht durch: an exception occurred while executing 'delete from `oc_documents_member` where `member_id` not in(select `m$","user":{"login":"hdering","id":3204979,"avatar_url":"https://gravatar.com/avatar/ba4f3e86161827f140f025408fdad390?d=https%3a%2f%2fidenticons.github.com%2f4015d7f209f430e141c9d7a10e5cf66a.png&r=x","gravatar_id":"ba4f3e86161827f140f025408fdad390","url":"https://api.github.com/users/hdering","html_url":"https://github.com/hdering","followers_url":"https://api.github.com/users/hdering/followers","following_url":"https://api.github.com/users/hdering/following{/other_user}","gists_url":"https://api.github.com/users/hdering/gists{/gist_id}","starred_url":"https://api.github.com/users/hdering/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/hdering/subscriptions","organizations_url":"https://api.github.com/users/hdering/orgs","repos_url":"https://api.github.com/users/hdering/repos","events_url":"https://api.github.com/users/hdering/events{/privacy}","received_events_url":"https://api.github.com/users/hdering/received_events","type":"user","site_admin":false},"labels":[],"state":"closed","assignee":null,"milestone":null,"comments":1,"created_at":"2013-11-29t07:49:58z","updated_at":"2013-11-29t08:40:16z","closed_at":"2013-11-29t08:40:16z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"hi guys,\r\n\r\ni updated my oc6-beta6 to oc6-rc1 and got the follow error message in my owncloud.log:\r\n...\r\n{\"app\":\"index\",\"message\":\"exception: 0 \\/var\\/www\\/clients\\/client1\\/web7\\/web\\/owncloud\\/lib\\/private\\/app.php(92): oc_app::checkupgrade('documents')\\n\",\"level\":4,\"time\":\"2013-11-28t15:13:36+00:00\"}\r\n{\"app\":\"index\",\"message\":\"exception: 1 \\/var\\/www\\/clients\\/client1\\/web7\\/web\\/owncloud\\/lib\\/private\\/app.php(66): oc_app::loadapp('documents')\\n\",\"level\":4,\"time\":\"2013-11-28t15:13:36+00:00\"}\r\n{\"app\":\"index\",\"message\":\"exception: 2 \\/var\\/www\\/clients\\/client1\\/web7\\/web\\/owncloud\\/lib\\/base.php(689): oc_app::loadapps()\\n\",\"level\":4,\"time\":\"2013-11-28t15:13:36+00:00\"}\r\n{\"app\":\"index\",\"message\":\"exception: 3 \\/var\\/www\\/clients\\/client1\\/web7\\/web\\/owncloud\\/index.php(30): oc::handlerequest()\\n\",\"level\":4,\"time\":\"2013-11-28t15:13:36+00:00\"}\r\n{\"app\":\"index\",\"message\":\"exception: 4 {main}\",\"level\":4,\"time\":\"2013-11-28t15:13:36+00:00\"}\r\n{\"app\":\"index\",\"message\":\"exception: konnte \\\"documents\\\" nicht aktualisieren. - verursacht durch: an exception occurred while executing 'delete from `oc_documents_member` where `member_id` not in(select `m$\r\n{\"app\":\"index\",\"message\":\"exception: konnte \\\"documents\\\" nicht aktualisieren. - verursacht durch: an exception occurred while executing 'delete from `oc_documents_member` where `member_id` not in(select `m$\r\n{\"app\":\"index\",\"message\":\"exception: konnte \\\"documents\\\" nicht aktualisieren.\",\"level\":4,\"time\":\"2013-11-28t15:13:37+00:00\"}\r\n{\"app\":\"index\",\"message\":\"exception: 0 \\/var\\/www\\/clients\\/client1\\/web7\\/web\\/owncloud\\/lib\\/private\\/app.php(92): oc_app::checkupgrade('documents')\\n\",\"level\":4,\"time\":\"2013-11-28t15:13:37+00:00\"}\r\n{\"app\":\"index\",\"message\":\"exception: 1 \\/var\\/www\\/clients\\/client1\\/web7\\/web\\/owncloud\\/lib\\/private\\/app.php(66): oc_app::loadapp('documents')\\n\",\"level\":4,\"time\":\"2013-11-28t15:13:37+00:00\"}\r\n{\"app\":\"index\",\"message\":\"exception: 2 \\/var\\/www\\/clients\\/client1\\/web7\\/web\\/owncloud\\/lib\\/base.php(689): oc_app::loadapps()\\n\",\"level\":4,\"time\":\"2013-11-28t15:13:37+00:00\"}\r\n{\"app\":\"index\",\"message\":\"exception: 3 \\/var\\/www\\/clients\\/client1\\/web7\\/web\\/owncloud\\/index.php(30): oc::handlerequest()\\n\",\"level\":4,\"time\":\"2013-11-28t15:13:37+00:00\"}\r\n{\"app\":\"index\",\"message\":\"exception: 4 {main}\",\"level\":4,\"time\":\"2013-11-28t15:13:37+00:00\"}\r\n{\"app\":\"index\",\"message\":\"exception: konnte \\\"documents\\\" nicht aktualisieren. - verursacht durch: an exception occurred while executing 'delete from `oc_documents_member` where `member_id` not in(select `m$\r\n{\"app\":\"index\",\"message\":\"exception: konnte \\\"documents\\\" nicht aktualisieren. - verursacht durch: an exception occurred while executing 'delete from `oc_documents_member` where `member_id` not in(select `m$\r\n{\"app\":\"cron\",\"message\":\"konnte \\\"documents\\\" nicht aktualisieren.\",\"level\":4,\"time\":\"2013-11-28t15:13:38+00:00\"}\r\n...\r\n\r\nafter i removed the line https://github.com/owncloud/documents/blob/master/appinfo/update.php#l15\r\nnow it works.\r\n\r\ni'm not alone with this problem:\r\nhttp://mail.kde.org/pipermail/owncloud/2013-november/011153.html\r\n\r\nhermann","closed_by":{"login":"kabum","id":245432,"avatar_url":"https://gravatar.com/avatar/a1dea19f88f38ea0b5b5b4d19d5b3107?d=https%3a%2f%2fidenticons.github.com%2f53d8cbb3dbc087a02951dec47438ccdf.png&r=x","gravatar_id":"a1dea19f88f38ea0b5b5b4d19d5b3107","url":"https://api.github.com/users/kabum","html_url":"https://github.com/kabum","followers_url":"https://api.github.com/users/kabum/followers","following_url":"https://api.github.com/users/kabum/following{/other_user}","gists_url":"https://api.github.com/users/kabum/gists{/gist_id}","starred_url":"https://api.github.com/users/kabum/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kabum/subscriptions","organizations_url":"https://api.github.com/users/kabum/orgs","repos_url":"https://api.github.com/users/kabum/repos","events_url":"https://api.github.com/users/kabum/events{/privacy}","received_events_url":"https://api.github.com/users/kabum/received_events","type":"user","site_admin":false}}