{"url":"https://api.github.com/repos/owncloud/core/issues/1139","labels_url":"https://api.github.com/repos/owncloud/core/issues/1139/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/1139/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/1139/events","html_url":"https://github.com/owncloud/core/issues/1139","id":9813617,"number":1139,"title":"client 1.2.0 crashes under ubuntu 12.04","user":{"login":"bertbrutzel","id":3227686,"avatar_url":"https://gravatar.com/avatar/8edf1401e6ad2fe6db7e77b7880bb43b?d=https%3a%2f%2fidenticons.github.com%2fe26d34896f29d4e25373d3a4178f70b7.png&r=x","gravatar_id":"8edf1401e6ad2fe6db7e77b7880bb43b","url":"https://api.github.com/users/bertbrutzel","html_url":"https://github.com/bertbrutzel","followers_url":"https://api.github.com/users/bertbrutzel/followers","following_url":"https://api.github.com/users/bertbrutzel/following{/other_user}","gists_url":"https://api.github.com/users/bertbrutzel/gists{/gist_id}","starred_url":"https://api.github.com/users/bertbrutzel/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/bertbrutzel/subscriptions","organizations_url":"https://api.github.com/users/bertbrutzel/orgs","repos_url":"https://api.github.com/users/bertbrutzel/repos","events_url":"https://api.github.com/users/bertbrutzel/events{/privacy}","received_events_url":"https://api.github.com/users/bertbrutzel/received_events","type":"user","site_admin":false},"labels":[],"state":"closed","assignee":null,"milestone":null,"comments":1,"created_at":"2013-01-09t17:30:15z","updated_at":"2013-01-09t19:02:01z","closed_at":"2013-01-09t19:02:01z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"good day,\r\n\r\nmy owncloud sync client started crashing right after start-up. the 1.2.0beta1 used to work just fine.\r\n\r\n$uname -a \r\nlinux pc-biotech99 3.2.0-35-generic #55-ubuntu smp wed dec 5 17:42:16\r\nutc 2012 x86_64 x86_64 x86_64 gnu/linux\r\n\r\n$dmesg\r\njan  9 18:20:46 pc-biotech99 kernel: [33425.650458] owncloud[15865]: segfault at 0 ip 00007f498a4c9fc7 sp 00007f495cfb0308 error 4 in libocsync.so.0.2.0[7f498a4b9000+1c000]\r\n\r\nlogfile:\r\n01-08 18:35:24:823 logging into logfile:  \"owncloud-crash.log\"  with flush  false \r\n01-08 18:35:24:823 \"################## owncloud de_de 1.2.0beta1 \" \r\n.\r\n.\r\n.\r\n.\r\n01-08 18:35:26:598     * csync thread started \r\n01-08 18:35:26:598     * event notification  disabled \r\n01-08 18:35:26:598 >===================================== sync started for  \"owncloud\" \r\n01-08 18:35:26:598   ==> returning exclude file path:  \"/etc/owncloud/sync-exclude.lst\" \r\n01-08 18:35:26:598 ==== added csync exclude list:  \"/etc/owncloud/sync-exclude.lst\" \r\n","closed_by":{"login":"deepdiver1975","id":1005065,"avatar_url":"https://gravatar.com/avatar/bdba071ed68da9ce8edae53c364902ef?d=https%3a%2f%2fidenticons.github.com%2f67e101ad9531b7d25697b76e503e062e.png&r=x","gravatar_id":"bdba071ed68da9ce8edae53c364902ef","url":"https://api.github.com/users/deepdiver1975","html_url":"https://github.com/deepdiver1975","followers_url":"https://api.github.com/users/deepdiver1975/followers","following_url":"https://api.github.com/users/deepdiver1975/following{/other_user}","gists_url":"https://api.github.com/users/deepdiver1975/gists{/gist_id}","starred_url":"https://api.github.com/users/deepdiver1975/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/deepdiver1975/subscriptions","organizations_url":"https://api.github.com/users/deepdiver1975/orgs","repos_url":"https://api.github.com/users/deepdiver1975/repos","events_url":"https://api.github.com/users/deepdiver1975/events{/privacy}","received_events_url":"https://api.github.com/users/deepdiver1975/received_events","type":"user","site_admin":false}}