{"url":"https://api.github.com/repos/owncloud/core/issues/2608","labels_url":"https://api.github.com/repos/owncloud/core/issues/2608/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/2608/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/2608/events","html_url":"https://github.com/owncloud/core/issues/2608","id":12578761,"number":2608,"title":"indexing stalls with php error message in oc 5.0","user":{"login":"bobhavlin","id":1026345,"avatar_url":"https://gravatar.com/avatar/836f2d5ab3802dae4d9790ac3ecf7465?d=https%3a%2f%2fidenticons.github.com%2fe132204fbe187563ce8f392a24c800db.png&r=x","gravatar_id":"836f2d5ab3802dae4d9790ac3ecf7465","url":"https://api.github.com/users/bobhavlin","html_url":"https://github.com/bobhavlin","followers_url":"https://api.github.com/users/bobhavlin/followers","following_url":"https://api.github.com/users/bobhavlin/following{/other_user}","gists_url":"https://api.github.com/users/bobhavlin/gists{/gist_id}","starred_url":"https://api.github.com/users/bobhavlin/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/bobhavlin/subscriptions","organizations_url":"https://api.github.com/users/bobhavlin/orgs","repos_url":"https://api.github.com/users/bobhavlin/repos","events_url":"https://api.github.com/users/bobhavlin/events{/privacy}","received_events_url":"https://api.github.com/users/bobhavlin/received_events","type":"user","site_admin":false},"labels":[],"state":"closed","assignee":null,"milestone":null,"comments":1,"created_at":"2013-03-28t18:52:25z","updated_at":"2013-03-28t20:49:17z","closed_at":"2013-03-28t20:49:17z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"i get the same message repeatedly (below) in the owncloud.log file and it appears as though the indexing has stalled - when i go to the search box it says: \"indexing... 48425 files left\" and has for days without the number changing.\r\n\r\nin my case, the files are linked into the data directory, which is what i guess is causing the error. any suggestion as to how to fix in 5.0?\r\n\r\n{\"app\":\"php\",\"message\":\"call to a member function removechild() on a non-object at \\/var\\/www\\/owncloud\\/apps\\/search_lucene\\/3rdparty\\/zend\\/search\\/lucene\\/document\\/html.php#117\",\"level\":4,\"time\":1364496303}\r\n","closed_by":{"login":"deepdiver1975","id":1005065,"avatar_url":"https://gravatar.com/avatar/bdba071ed68da9ce8edae53c364902ef?d=https%3a%2f%2fidenticons.github.com%2f67e101ad9531b7d25697b76e503e062e.png&r=x","gravatar_id":"bdba071ed68da9ce8edae53c364902ef","url":"https://api.github.com/users/deepdiver1975","html_url":"https://github.com/deepdiver1975","followers_url":"https://api.github.com/users/deepdiver1975/followers","following_url":"https://api.github.com/users/deepdiver1975/following{/other_user}","gists_url":"https://api.github.com/users/deepdiver1975/gists{/gist_id}","starred_url":"https://api.github.com/users/deepdiver1975/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/deepdiver1975/subscriptions","organizations_url":"https://api.github.com/users/deepdiver1975/orgs","repos_url":"https://api.github.com/users/deepdiver1975/repos","events_url":"https://api.github.com/users/deepdiver1975/events{/privacy}","received_events_url":"https://api.github.com/users/deepdiver1975/received_events","type":"user","site_admin":false}}