{"url":"https://api.github.com/repos/owncloud/core/issues/6411","labels_url":"https://api.github.com/repos/owncloud/core/issues/6411/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/6411/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/6411/events","html_url":"https://github.com/owncloud/core/issues/6411","id":24282298,"number":6411,"title":"oc6 keeps losing encryption keys","user":{"login":"philfry","id":1649785,"avatar_url":"https://gravatar.com/avatar/4030a2833ea810bff6677bc77869cdf2?d=https%3a%2f%2fidenticons.github.com%2fc9ef6acf15644d2e7568ca3b57e6e014.png&r=x","gravatar_id":"4030a2833ea810bff6677bc77869cdf2","url":"https://api.github.com/users/philfry","html_url":"https://github.com/philfry","followers_url":"https://api.github.com/users/philfry/followers","following_url":"https://api.github.com/users/philfry/following{/other_user}","gists_url":"https://api.github.com/users/philfry/gists{/gist_id}","starred_url":"https://api.github.com/users/philfry/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/philfry/subscriptions","organizations_url":"https://api.github.com/users/philfry/orgs","repos_url":"https://api.github.com/users/philfry/repos","events_url":"https://api.github.com/users/philfry/events{/privacy}","received_events_url":"https://api.github.com/users/philfry/received_events","type":"user","site_admin":false},"labels":[{"url":"https://api.github.com/repos/owncloud/core/labels/app%3afiles_encryption","name":"app:files_encryption","color":"02d7e1"},{"url":"https://api.github.com/repos/owncloud/core/labels/bug","name":"bug","color":"fc2929"}],"state":"closed","assignee":null,"milestone":null,"comments":18,"created_at":"2013-12-14t00:54:13z","updated_at":"2013-12-16t16:52:07z","closed_at":"2013-12-16t16:52:07z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"hi everyone,\r\n\r\ni'm using the encryption app.\r\nafter updating to oc6 and logging in all my key files were lost (and so was my data). fortunately, i still had a copy on a machine that didn't sync yet.\r\nnow i try to upload the data again folder by folder and the keys are being generated.\r\nbut after a while the key files vanish, leaving my data unreadable again. i'm using the owncloud client to sync my data, and the former folder's key files seem to vanish after the sync to the server has completed.\r\n\r\nthe server log file shows\r\n```\r\n{\"app\":\"encryption library\",\"message\":\"could not delete keyfile; does not exist: \\\"\\/phil\\/files_encryption\\/keyfiles\\/\",\"level\":3,\"time\":\"2013-12-13t23:50:07+00:00\"}\r\n{\"app\":\"encryption library\",\"message\":\"keyfile or sharekey could not be deleted for file \\\"\\/\\\"\",\"level\":3,\"time\":\"2013-12-13t23:50:07+00:00\"}\r\n{\"app\":\"encryption library\",\"message\":\"\\\"phil\\\" is not setup for encryption\",\"level\":2,\"time\":\"2013-12-13t23:50:07+00:00\"}\r\n{\"app\":\"php\",\"message\":\"openssl_seal(): fourth argument to openssl_seal() must be a non-empty array at \\/var\\/www\\/html\\/owncloud\\/apps\\/files_encryption\\/lib\\/crypt.php#410\",\"level\":2,\"time\":\"2013-12-13t23:50:07+00:00\"}\r\n{\"app\":\"php\",\"message\":\"missing argument 2 for oc\\\\files\\\\storage\\\\local::file_put_contents(), called in \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/view.php on line 684 and defined at \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/storage\\/local.php#153\",\"level\":2,\"time\":\"2013-12-13t23:50:07+00:00\"}\r\n{\"app\":\"php\",\"message\":\"undefined variable: data at \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/storage\\/local.php#154\",\"level\":2,\"time\":\"2013-12-13t23:50:07+00:00\"}\r\n{\"app\":\"php\",\"message\":\"argument 4 passed to oca\\\\encryption\\\\keymanager::setsharekeys() must be an array, null given, called in \\/var\\/www\\/html\\/owncloud\\/apps\\/files_encryption\\/lib\\/stream.php on line 534 and defined at \\/var\\/www\\/html\\/owncloud\\/apps\\/files_encryption\\/lib\\/keymanager.php#320\",\"level\":2,\"time\":\"2013-12-13t23:50:07+00:00\"}\r\n{\"app\":\"php\",\"message\":\"invalid argument supplied for foreach() at \\/var\\/www\\/html\\/owncloud\\/apps\\/files_encryption\\/lib\\/keymanager.php#338\",\"level\":2,\"time\":\"2013-12-13t23:50:07+00:00\"}\r\n{\"app\":\"hook\",\"message\":\"error while running hook (oc\\\\preview::post_write): encryption key not found for \\\"\\/phil\\/files\\/docswork\\/somefile.bin\\\" during attempted read via stream\",\"level\":3,\"time\":\"2013-12-13t23:50:07+00:00\"}\r\n{\"app\":\"index\",\"message\":\"exception: encryption key not found for \\\"\\/phil\\/files\\/docswork\\/anotherfile.txt\\\" during attempted read via stream\",\"level\":4,\"time\":\"2013-12-14t00:26:58+00:00\"}\r\n```\r\n\r\nto me it looks fscked up really bad. for now, i am unable to store any data in oc without losing it.\r\n\r\nany clues?\r\n\r\nregards,\r\n\r\nphil","closed_by":{"login":"schiesbn","id":1589737,"avatar_url":"https://gravatar.com/avatar/8912b598c7b32dd25b87fd168e0b06b2?d=https%3a%2f%2fidenticons.github.com%2f0a323047dbe8329db30eae8dbe96e55e.png&r=x","gravatar_id":"8912b598c7b32dd25b87fd168e0b06b2","url":"https://api.github.com/users/schiesbn","html_url":"https://github.com/schiesbn","followers_url":"https://api.github.com/users/schiesbn/followers","following_url":"https://api.github.com/users/schiesbn/following{/other_user}","gists_url":"https://api.github.com/users/schiesbn/gists{/gist_id}","starred_url":"https://api.github.com/users/schiesbn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/schiesbn/subscriptions","organizations_url":"https://api.github.com/users/schiesbn/orgs","repos_url":"https://api.github.com/users/schiesbn/repos","events_url":"https://api.github.com/users/schiesbn/events{/privacy}","received_events_url":"https://api.github.com/users/schiesbn/received_events","type":"user","site_admin":false}}