{"url":"https://api.github.com/repos/owncloud/core/issues/1009","labels_url":"https://api.github.com/repos/owncloud/core/issues/1009/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/1009/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/1009/events","html_url":"https://github.com/owncloud/core/issues/1009","id":9484303,"number":1009,"title":"sabredav memory allocation failure","user":{"login":"klamann","id":1008877,"avatar_url":"https://gravatar.com/avatar/193d1a7bd020061f74afd8769ce32492?d=https%3a%2f%2fidenticons.github.com%2f28b34c9ae223280bd95949d2aa8e1567.png&r=x","gravatar_id":"193d1a7bd020061f74afd8769ce32492","url":"https://api.github.com/users/klamann","html_url":"https://github.com/klamann","followers_url":"https://api.github.com/users/klamann/followers","following_url":"https://api.github.com/users/klamann/following{/other_user}","gists_url":"https://api.github.com/users/klamann/gists{/gist_id}","starred_url":"https://api.github.com/users/klamann/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/klamann/subscriptions","organizations_url":"https://api.github.com/users/klamann/orgs","repos_url":"https://api.github.com/users/klamann/repos","events_url":"https://api.github.com/users/klamann/events{/privacy}","received_events_url":"https://api.github.com/users/klamann/received_events","type":"user","site_admin":false},"labels":[{"url":"https://api.github.com/repos/owncloud/core/labels/bug","name":"bug","color":"fc2929"}],"state":"closed","assignee":null,"milestone":null,"comments":4,"created_at":"2012-12-22t15:32:06z","updated_at":"2013-04-24t10:54:48z","closed_at":"2013-04-24t10:54:48z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"i keep getting this error that ultimately caused my server to run havoc last night, when it filled the apache error.log up to 16gb with the following message:\r\n\r\n    [thu dec 21 23:25:11 2012] [error] [client 92.x.x.x] php warning:  domdocument::savexml(): memory allocation failed :\r\n    growing buffer in /var/www/httpdocs/owncloud/3rdparty/sabre/dav/server.php on line 1933\r\n\r\ni'm using owncloud 4.5.2 in combination with the windows client application. ownclouds own log files don't show any traces of errors. let me know if you need any additional information.","closed_by":{"login":"guruz","id":959327,"avatar_url":"https://gravatar.com/avatar/a20dd2f596a7c3e61517ecf260cb2cf6?d=https%3a%2f%2fidenticons.github.com%2fe39fcffedd172d9f75cf9bc7eff42716.png&r=x","gravatar_id":"a20dd2f596a7c3e61517ecf260cb2cf6","url":"https://api.github.com/users/guruz","html_url":"https://github.com/guruz","followers_url":"https://api.github.com/users/guruz/followers","following_url":"https://api.github.com/users/guruz/following{/other_user}","gists_url":"https://api.github.com/users/guruz/gists{/gist_id}","starred_url":"https://api.github.com/users/guruz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/guruz/subscriptions","organizations_url":"https://api.github.com/users/guruz/orgs","repos_url":"https://api.github.com/users/guruz/repos","events_url":"https://api.github.com/users/guruz/events{/privacy}","received_events_url":"https://api.github.com/users/guruz/received_events","type":"user","site_admin":false}}